### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by gklka** [gklka/GKActionSheetPicker#1]
Add a title between the buttons

**Comment by gklka** [comment]
Title is implemented in version 0.3

**Comment by osmer** [comment]
Set title doesn't work on Swift 3.0. I could not assign the title. I added tag 0.3 into my pods.

**Comment by gklka** [comment]
How do you set it?

**Comment by osmer** [comment]
pod 'GKActionSheetPicker', :git => 'https://github.com/gklka/GKActionSheetPicker', :tag => '0.3'

I tried with too:

pod 'GKActionSheetPicker'

**Comment by gklka** [comment]
I mean how do you try to set the title?
